#list of Viviano-Beck et al., 2014 spectral parameters

spectral_parameters = [
    ("R770",       "0.77 µm reflectance",                 "Higher = dusty / icy surfaces"),
    ("RBR",        "Red / Blue ratio",                    "Higher = more npFeOx"),
    ("BD530_2",    "0.53 µm band depth",                 "Fine-grained crystalline hematite"),
    ("SH600_2",    "0.60 µm shoulder height",            "Ferric minerals / hematite / goethite"),
    ("SH770",      "0.77 µm shoulder height",            "Ferric minerals"),
    ("BD640_2",    "0.64 µm band depth",                "Maghemite / ferric minerals"),
    ("BD860_2",    "0.86 µm band depth",                "Crystalline ferric minerals"),
    ("BD920_2",    "0.92 µm band depth",                "Ferric minerals + LCP"),
    ("RPEAK1",     "Reflectance peak position",          "Fe mineralogy / olivine / pyroxene / dust"),
    ("BDI1000VIS", "1 µm integrated band depth (VNIR)",  "Olivine / pyroxene / Fe glass"),
    ("BDI1000IR",  "1 µm integrated band depth (IR)",    "Crystalline Fe²⁺ silicates"),
    ("R1330",      "1.33 µm reflectance",               "IR albedo"),
    ("BD1300",     "1.3 µm absorption",                 "Fe-bearing plagioclase"),
    ("OLINDEX3",   "1 µm broad absorption",             "Olivine detection"),
    ("LCPINDEX2",  "1.81 µm absorption",                "Low-Ca pyroxene"),
    ("HCPINDEX2",  "2.12 µm absorption",                "High-Ca pyroxene"),
    ("VAR",        "1.0–2.3 µm spectral variance",      "Strong mafic minerals"),
    ("ISLOPE1",    "Spectral slope",                    "Ferric coating"),
    ("BD1400",     "1.4 µm band depth",                "Hydrated / OH minerals"),
    ("BD1435",     "1.435 µm band depth",              "CO2 ice"),
    ("BD1500_2",   "1.5 µm band depth",                "H2O ice"),
    ("ICER1_2",    "CO2/H2O ice ratio",                "Ice mixture indicator"),
    ("BD1750_2",   "1.75 µm band depth",               "Gypsum / Alunite"),
    ("BD1900_2",   "1.9 µm band depth",                "Bound water"),
    ("BD1900R2",   "1.9 µm band depth refined",        "H2O"),
    ("BDI2000",    "2 µm integrated band depth",       "Pyroxene"),
    ("BD2100_2",   "2.1 µm band depth",                "Monohydrated sulfates"),
    ("BD2165",     "2.165 µm band depth",              "Pyrophyllite / Kaolinite"),
    ("BD2190",     "2.19 µm band depth",               "Beidellite"),
    ("MIN2200",    "2.2 µm doublet minimum",           "Kaolinite group"),
    ("BD2210_2",   "2.21 µm band depth",              "Al-OH minerals"),
    ("D2200",      "2.2 µm dropoff",                  "Al-OH minerals"),
    ("BD2230",     "2.23 µm band depth",              "Ferric sulfate"),
    ("BD2250",     "2.25 µm band depth",              "Opal / Al-OH"),
    ("MIN2250",    "2.25 µm minimum",                 "Opal"),
    ("BD2265",     "2.265 µm band depth",             "Jarosite"),
    ("BD2290",     "2.29 µm band depth",              "Mg/Fe-OH minerals"),
    ("D2300",      "2.3 µm dropoff",                  "Fe/Mg phyllosilicates"),
    ("BD2355",     "2.355 µm band depth",             "Chlorite / Prehnite"),
    ("SINDEX2",    "2.29 µm convexity",               "Hydrated sulfates"),
    ("ICER2_2",    "2.7 µm CO2 ice index",            "CO2 vs water ice"),
    ("MIN2295_2480","Carbonate double absorption",     "Mg carbonates"),
    ("MIN2345_2537","Carbonate double absorption",     "Ca/Fe carbonates"),
    ("BD2500_2",   "2.5 µm band depth",               "Mg carbonates"),
    ("BD3000",     "3 µm band depth",                 "Bound H2O"),
    ("BD3100",     "3.1 µm band depth",               "H2O ice"),
    ("BD3200",     "3.2 µm band depth",               "CO2 ice"),
    ("BD3400_2",   "3.4 µm band depth",               "Carbonates"),
    ("CINDEX2",    "3.6 µm convexity",               "Carbonates"),
]
